[application]
name = "SmarterBuaa"
default_platform = "desktop"
asset_dir = "static"
# android_manifest = ""

[web.app]
title = "SmarterBuaa"

[bundle]
identifier = "com.fontlos.smarterbuaa"
publisher = "Fontlos"
icon = [
    "assets/logo.png",
    "assets/logo.svg"
]
copyright = "Copyright 2025 Fontlos"
category = "Utility"
short_description = "MAKE BUAA GREAT AGAIN"
long_description = """
A more powerful third-party app of something you know.
This project is only for learning and sharing,
please delete within 24 hours after downloading,
all problems caused by the use are borne by the user,
if there is any infringement I will delete this repository and software
"""
